CREATE TABLE GAME ( 
    ID                integer NOT NULL,
    NAME              varchar(15) NOT NULL,
    CONSTRAINT PK_GAME PRIMARY KEY (ID)
 );

CREATE TABLE DRAW ( 
    ID                integer NOT NULL,
    DRAW_DATE         date NOT NULL,
    COLUMNS           integer NOT NULL,
    GAME_ID           integer NOT NULL,
    CONSTRAINT PK_DRAW PRIMARY KEY (ID)
 );

CREATE TABLE PRIZE ( 
    ID                integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CATEGORY_NUMBER   integer NOT NULL,
    DIVIDENT          integer NOT NULL,
    WINNERS           integer NOT NULL,
    PROFIT            integer NOT NULL,
    DRAW_ID           integer NOT NULL,
    CONSTRAINT PK_PRIZE PRIMARY KEY (ID)
 );

CREATE TABLE WIN_NUMBER ( 
    ID                integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NUMBER            varchar(2) NOT NULL,
    TYPE              char(1) NOT NULL,
    DRAW_ID           integer NOT NULL,
    CONSTRAINT PK_WIN_NUMBER PRIMARY KEY (ID)
 );

ALTER TABLE DRAW ADD CONSTRAINT FK_DRAW_GAME FOREIGN KEY (GAME_ID) REFERENCES GAME(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PRIZE ADD CONSTRAINT FK_PRIZE_DRAW FOREIGN KEY (DRAW_ID) REFERENCES DRAW(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE WIN_NUMBER ADD CONSTRAINT FK_WIN_NUMBER_DRAW FOREIGN KEY (DRAW_ID) REFERENCES DRAW(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;