package view;

import controller.DBCompleteness;
import controller.Graph;
import controller.NumbersFreqGraph;
import controller.TzokersFreqGraph;
import controller.WinningAvgGraph;
import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import service.DateParser;
import service.DateRange;
import service.FetchData;
import service.Utils;

public class Charts extends javax.swing.JPanel {
    private DateRange dateRange;
    private SwingWorker<Integer, Integer> worker;
    private DBCompleteness complete;
    
    /**
     * Creates new form Charts
     */
    public Charts() {
        initComponents();
        
        produceDates();
        resultLabel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateFromField = new javax.swing.JFormattedTextField();
        dateToField = new javax.swing.JFormattedTextField();
        buttonsPanel = new javax.swing.JPanel();
        numberFreqBtn = new javax.swing.JButton();
        tzokersFreqBtn = new javax.swing.JButton();
        winningAvgBtn = new javax.swing.JButton();
        graphicsPanel = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        resultLabel.setBackground(new java.awt.Color(255, 255, 255));
        resultLabel.setForeground(new java.awt.Color(0, 0, 0));
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel5.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ημερομηνίες");
        jPanel5.add(jLabel1);

        dateFromField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        dateFromField.setToolTipText("YYYY-MM-dd");
        dateFromField.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(dateFromField);

        dateToField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        dateToField.setToolTipText("YYYY-MM-dd");
        dateToField.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(dateToField);

        buttonsPanel.setOpaque(false);

        numberFreqBtn.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        numberFreqBtn.setText("Συχνότητα Αριθμών");
        numberFreqBtn.setAlignmentX(0.5F);
        numberFreqBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numberFreqBtn.setPreferredSize(new java.awt.Dimension(210, 31));
        numberFreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFreqBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(numberFreqBtn);

        tzokersFreqBtn.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        tzokersFreqBtn.setText("Συχνότητα Αριθμών τζόκερ");
        tzokersFreqBtn.setAlignmentX(0.5F);
        tzokersFreqBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tzokersFreqBtn.setPreferredSize(new java.awt.Dimension(210, 31));
        tzokersFreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tzokersFreqBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(tzokersFreqBtn);

        winningAvgBtn.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        winningAvgBtn.setText("Μ.Ο. κερδών ανά κατηγορία");
        winningAvgBtn.setAlignmentX(0.5F);
        winningAvgBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        winningAvgBtn.setPreferredSize(new java.awt.Dimension(210, 31));
        winningAvgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winningAvgBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(winningAvgBtn);

        graphicsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Γεμίζει τα text fields των ημερομηνιών με την σημερινή ημερομηνία και την
    // αντίστοιχη 3 μήνες πριν
    private void produceDates() {
        dateToField.setText(Utils.getTodayDate());
        dateFromField.setText(Utils.getThreeMonthsAgoDate());
    }
    
    // Ελέγει την πληρότητα της βάσης
    private void checkDBCompleteness() {
        // Δημιουργεί Swing Worker για να τρέξει την άντληση των δεδομένων σε thread
        worker = new SwingWorker<Integer, Integer>() {
            @Override
            protected Integer doInBackground() throws Exception {
                // Εμφανίζει την πληρότητα της βάσης
                complete = new DBCompleteness(dateRange);
                complete.setWorker(this::publish);
                complete.calculate();

                return 0;
            }
            
            @Override
            protected void process(List<Integer> chunks) {
                for (Integer value : chunks) {
                    resultLabel.setText("Έλεγχος πληρότητας της βάσης δεδομένων... (" + value + "%)");
                }
            }
            
            @Override
            protected void done() {
                resultLabel.setText(complete.getResult());
            }
        };

        resultLabel.setVisible(true);
        worker.execute();
    }
    
    // Εμφανίζει το αντίστοιχο γράφημα
    private void createGraph(Graph graph) {
        // Δημιουργεί Swing Worker για να τρέξει την άντληση των δεδομένων σε thread
        worker = new SwingWorker<Integer, Integer>() {
            @Override
            protected Integer doInBackground() throws Exception {
                graph.setDateRange(dateRange);
                graphicsPanel.add(graph.create());
                
                checkDBCompleteness();
                
                return 0;
            }
            
            @Override
            protected void done() {
                numberFreqBtn.setEnabled(true);
                tzokersFreqBtn.setEnabled(true);
                winningAvgBtn.setEnabled(true);
                graphicsPanel.setVisible(true);
                graphicsPanel.revalidate();
                
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        };
        
        // Παίρνει το εύρος ημερομηνιών σε αντικείμενο DateRange
        DateParser parser = new DateParser(dateFromField.getText(), dateToField.getText());
        dateRange = parser.get();
        
        // Αν υπάρξει σφάλμα διακόπτει την εκτέλεση
        if (dateRange == null) {
            return;
        }
        
        // Έλεγχος αν υπάρχουν δεδομένα στο συγκεκριμένο εύρος
        FetchData fetch = new FetchData();
        if (fetch.getDrawsInRange(dateRange).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Δεν υπάρχουν δεδομένα στη βάση δεδομένων", "Σφάλμα", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Διάφορες αρχικοποιήσεις
        graphicsPanel.removeAll();
        resultLabel.setVisible(false);
        resultLabel.setText("");
        numberFreqBtn.setEnabled(false);
        tzokersFreqBtn.setEnabled(false);
        winningAvgBtn.setEnabled(false);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        // Εκτέλεση του worker
        worker.execute();
    }
    
    
    private void numberFreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFreqBtnActionPerformed
        createGraph(new NumbersFreqGraph());
    }//GEN-LAST:event_numberFreqBtnActionPerformed

    private void tzokersFreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tzokersFreqBtnActionPerformed
        createGraph(new TzokersFreqGraph());
    }//GEN-LAST:event_tzokersFreqBtnActionPerformed

    private void winningAvgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winningAvgBtnActionPerformed
        createGraph(new WinningAvgGraph());
    }//GEN-LAST:event_winningAvgBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JFormattedTextField dateFromField;
    private javax.swing.JFormattedTextField dateToField;
    private javax.swing.JPanel graphicsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton numberFreqBtn;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton tzokersFreqBtn;
    private javax.swing.JButton winningAvgBtn;
    // End of variables declaration//GEN-END:variables
}
